import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bannersScreen: {
    width: '100%',
    position: 'relative',
    height: 874,
    textAlign: 'center',
    fontSize: 32,
    color: '#000',
    fontFamily: 'Bungee', // Ensure this font is available in your project
  },
  bannersScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 412,
    height: 917,
    resizeMode: 'cover', // React Native equivalent of object-fit: cover
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 63,
    left: 2,
    width: 48,
    height: 48,
    overflow: 'hidden',
  },
  arrowLeftIconImage: {
    width: '100%',
    height: '100%',
  },
  banners: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '7.21%',
    left: '4.48%',
    fontSize: 48,
    fontFamily: 'Bungee Shade',
    color: '#fff',
    textAlign: 'center',
    alignSelf: 'center',
  },
  banner3Child: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#3498db',
    width: 337,
    height: 92,
    opacity: 0.75,
  },
  tba: {
    position: 'absolute',
    height: '95.65%',
    width: '100%',
    top: '4.35%',
    left: 0,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 16,
    color: '#fff',
  },
  banner3: {
    position: 'absolute',
    top: 603,
    left: 32,
    width: 337,
    height: 92,
  },
  banner2: {
    position: 'absolute',
    top: 408,
    left: 40,
    width: 337,
    height: 92,
  },
  banner1: {
    position: 'absolute',
    top: 201,
    left: 32,
    width: 337,
    height: 92,
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
});
