import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  beastsScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 412,
    height: 917,
    resizeMode: 'cover',
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 63,
    left: 2,
    width: 48,
    height: 48,
    overflow: 'hidden',
  },
  beasts: {
    position: 'absolute',
    height: '15.79%',
    width: '95.02%',
    top: '7.21%',
    left: '4.48%',
    fontSize: 48,
    fontFamily: 'Bungee Shade',
    color: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  beasts3Child: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#3498db',
    width: 337,
    height: 92,
    opacity: 0.75,
  },
  tba: {
    position: 'absolute',
    height: '95.65%',
    width: '100%',
    top: '4.35%',
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  beasts3: {
    position: 'absolute',
    top: 603,
    left: 32,
    width: 337,
    height: 92,
  },
  beasts2Child: {
    position: 'absolute',
    top: 0,
    left: 8,
    backgroundColor: '#3498db',
    width: 337,
    height: 92,
    opacity: 0.75,
  },
  tba1: {
    position: 'absolute',
    height: '95.65%',
    width: '97.68%',
    top: '4.35%',
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  beasts2: {
    position: 'absolute',
    top: 408,
    left: 32,
    width: 345,
    height: 92,
  },
  beasts1: {
    position: 'absolute',
    top: 201,
    left: 32,
    width: 337,
    height: 92,
  },
  beastsScreen: {
    width: '100%',
    position: 'relative',
    height: 874,
    textAlign: 'center',
    fontSize: 32,
    color: '#000',
    fontFamily: 'Bungee',
  },
});

export default styles;
