// src/styles/CreateAccountScreenStyles.ts
import { StyleSheet } from 'react-native';

const createAccountScreenStyles = StyleSheet.create({
    createAccountScreen: {
        width: '100%',
        position: 'relative',
        height: 874, // Adjust this value based on your design
        backgroundColor: '#fff', // Or any other background color you prefer
        textAlign: 'left',
        fontSize: 16,
        color: '#b3b3b3',
        fontFamily: 'Inter',
      },
      backgroundImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: -1, // Ensures the background image is behind other content
      },
  createAccountScreenChild: {
    position: 'absolute',
    height: '104.92%',
    width: '102.49%',
    top: '0%',
    right: '-2.49%',
    bottom: '-4.92%',
    left: '0%',
    backgroundColor: 'rgba(210, 224, 253, 0.5)', // Linear gradient equivalent
  },
  haveAnAccount: {
    position: 'absolute',
    top: 705,
    left: 124,
    fontSize: 20,
    fontFamily: 'Exo',
    color: '#f9c74f',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 154,
  },
  barRight: {
    position: 'absolute',
    top: 2,
    left: 320,
    borderRadius: 50,
    backgroundColor: '#1e1e1e',
    borderColor: '#f9c74f',
    borderWidth: 1,
    width: 40,
    height: 40,
  },
  barLeft: {
    position: 'absolute',
    top: 2,
    left: 5,
    borderRadius: 50,
    backgroundColor: '#1e1e1e',
    borderColor: '#f9c74f',
    borderWidth: 1,
    width: 40,
    height: 40,
  },
  bar: {
    position: 'absolute',
    top: 2,
    left: 25,
    backgroundColor: '#1e1e1e',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#f9c74f',
    width: 315,
    height: 40,
  },
  login: {
    position: 'absolute',
    top: 10,
    left: 144,
  },
  loginButton: {
    position: 'absolute',
    top: 783,
    left: 20,
    width: 364,
    height: 42,
    overflow: 'hidden',
    fontSize: 24,
    color: '#f9c74f',
    fontFamily: 'Gruppo',
  },
  username: {
    flex: 1,
    position: 'relative',
    lineHeight: 24,  // Set a numeric value for lineHeight
  },
  input: {
    alignSelf: 'stretch',
    flex: 1,
    borderRadius: 8,
    backgroundColor: '#1e1e1e',
    borderColor: '#f9c74f',
    borderWidth: 1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 12,
    minWidth: 240,
  },
  usernameField: {
    position: 'absolute',
    top: 407,
    left: 41,
    width: 320,
    height: 50,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  passwordField: {
    position: 'absolute',
    top: 503,
    left: 41,
    width: 320,
    height: 50,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  confirmpasswordField: {
    position: 'absolute',
    top: 589,
    left: 41,
    width: 320,
    height: 50,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    cursor: 'pointer',
  },
  dj: {
    margin: 0,
  },
  djCompanionTxt: {
    // Removed lineBreak, use flexWrap for text wrapping
    width: '100%',
    flexWrap: 'wrap',  // Will allow text to wrap
  },
  djCompanion: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '7.89%',
    left: '4.48%',
    fontSize: 48,
    display: 'flex',
    fontFamily: 'Playfair Display',
    color: '#3a3a3a',
    textAlign: 'center',
    alignItems: 'center',
    // Text shadow in React Native
    textShadowColor: '#e74c3c',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 4,
  },
  track1: {
    position: 'absolute',
    width: '100%',
    top: '50%',
    right: 0,
    left: 0,
    borderRadius: 8,
    backgroundColor: '#f9c74f',
    height: 4,
  },
  track: {
    flex: 1,
    position: 'relative',
    height: 12,
    zIndex: 0,
  },
  stopShape: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    borderRadius: 26,
    backgroundColor: '#f9c74f',
    width: 4,
    height: 4,
  },
  stop: {
    width: 4,
    position: 'absolute',
    margin: 0,
    top: '50%',
    right: 0,
    height: 4,
    zIndex: 1,
  },
  trackAndStop: {
    position: 'absolute',
    width: '100%',
    top: '50%',
    right: 0,
    left: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 0,
  },
  linearDeterminateProgressIn: {
    position: 'absolute',
    top: 685,
    left: 18,
    width: 106,
    height: 98,
    overflow: 'hidden',
  },
  linearDeterminateProgressIn1: {
    position: 'absolute',
    top: 685,
    left: 278,
    width: 106,
    height: 98,
    overflow: 'hidden',
  },
});

export default createAccountScreenStyles;
