import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  forumTopicsScreen: {
    flex: 1,
    position: 'relative',
    textAlign: 'center',
    fontSize: 15,
    color: '#f9c74f',
    fontFamily: 'Bungee', // Ensure this font is available
  },
  forumTopicsScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 917,
    resizeMode: 'cover',
  },
  topics: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '7.21%',
    left: '4.48%',
    fontSize: 48,
    fontFamily: 'Bungee Shade',
    color: '#fff',
    textAlign: 'center',
    alignSelf: 'center',
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 63,
    left: 2,
    width: 48,
    height: 48,
    overflow: 'hidden',
  },
  arrowLeftIconImage: {
    width: '100%',
    height: '100%',
  },
  selector: {
    position: 'absolute',
    top: 201,
    left: 0,
    backgroundColor: '#000',
    width: 374,
    height: 582,
  },
  categorySixChild: {
    position: 'absolute',
    top: 10,
    left: 11,
    backgroundColor: '#d9d9d9',
    width: 375,
    height: 68,
    opacity: 0.7,
  },
  alexH: {
    position: 'absolute',
    top: '82%',
    left: '5.05%',
  },
  div: {
    position: 'absolute',
    top: '81.52%',
    left: '82.22%',
  },
  contests: {
    position: 'absolute',
    height: '88%',
    width: '100%',
    top: 0,
    left: 0,
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categorySix: {
    position: 'absolute',
    top: 191,
    left: -11,
    width: 396,
    height: 100,
  },
  categoryFiveChild: {
    position: 'absolute',
    top: 10,
    left: 0,
    backgroundColor: '#d9d9d9',
    width: 375,
    height: 68,
    opacity: 0.7,
  },
  alexH1: {
    position: 'absolute',
    top: '82.86%',
    left: '2.13%',
  },
  div1: {
    position: 'absolute',
    top: '79.05%',
    left: '83.73%',
  },
  fanworks: {
    position: 'absolute',
    height: '83.81%',
    width: '98.93%',
    top: 0,
    left: '0.27%',
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categoryFive: {
    position: 'absolute',
    top: 287,
    left: 0,
    width: 375,
    height: 105,
  },
  categoryFourChild: {
    position: 'absolute',
    top: 15,
    left: 0,
    backgroundColor: '#d9d9d9',
    width: 375,
    height: 68,
    opacity: 0.7,
  },
  alexH2: {
    position: 'absolute',
    top: '83.02%',
    left: '2.13%',
  },
  div2: {
    position: 'absolute',
    top: '83.02%',
    left: '84.27%',
  },
  tacticsDiscussion: {
    position: 'absolute',
    height: '83.02%',
    width: '98.93%',
    top: 0,
    left: '0.27%',
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categoryFour: {
    position: 'absolute',
    top: 378,
    left: 0,
    width: 375,
    height: 106,
  },
  categoryThreeChild: {
    position: 'absolute',
    top: 9,
    left: 0,
    backgroundColor: '#d9d9d9',
    width: 375,
    height: 68,
    opacity: 0.7,
  },
  alexH3: {
    position: 'absolute',
    top: '82%',
    left: '1.6%',
  },
  div3: {
    position: 'absolute',
    top: '82%',
    left: '82.4%',
  },
  storyeventsDiscussion: {
    position: 'absolute',
    height: '88%',
    width: '98.93%',
    top: 0,
    left: '0.27%',
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categoryThree: {
    position: 'absolute',
    top: 480,
    left: 2,
    width: 375,
    height: 100,
  },
  alexH4: {
    position: 'absolute',
    top: '78.22%',
    left: '2.4%',
  },
  div4: {
    position: 'absolute',
    top: '82.18%',
    left: '84.27%',
  },
  bannersDiscussion: {
    position: 'absolute',
    height: '87.13%',
    width: '98.93%',
    top: 0,
    left: '0.8%',
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categoryTwo: {
    position: 'absolute',
    top: 575,
    left: -1,
    width: 375,
    height: 101,
  },
  alexH5: {
    position: 'absolute',
    top: '82.35%',
    left: '2.4%',
  },
  div5: {
    position: 'absolute',
    top: '81.37%',
    left: '86.4%',
  },
  charactersDiscussion: {
    position: 'absolute',
    height: '86.27%',
    width: '98.93%',
    top: 0,
    left: 0,
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    alignSelf: 'center',
  },
  categoryOne: {
    position: 'absolute',
    top: 671,
    left: -1,
    width: 375,
    height: 102,
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
});
