// styles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  forumHomeScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 917,
    resizeMode: 'cover', // Equivalent to object-fit: cover
  },
  forumHome: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '7.21%',
    left: '4.48%',
    fontSize: 48,
    fontFamily: 'Bungee Shade', // Referencing global font styles if necessary
    color: '#fff',
    textAlign: 'center',
    alignItems: 'center',
  },
  forum: {
    margin: 0,
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 63,
    left: 2,
    width: 48,
    height: 48,
  },
  arrowLeftIconImage: {
    width: '100%',
    height: '100%',
  },
  grouping: {
    position: 'absolute',
    top: 201,
    left: 47,
    backgroundColor: '#f9c74f',
    width: 307,
    height: 543,
    opacity: 0.7,
  },
  newsGameChild: {
    position: 'absolute',
    top: 11,
    left: 0,
    backgroundColor: '#ff0000',
    width: 307,
    height: 66,
    opacity: 0.5,
  },
  newsGame1: {
    position: 'absolute',
    height: '100%',
    width: '94.46%',
    top: 0,
    left: '2.93%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  newsGame: {
    position: 'absolute',
    top: 190,
    left: 47,
    width: 307,
    height: 88,
    cursor: 'pointer',
  },
  newsApp1: {
    position: 'absolute',
    height: '100%',
    width: '94.46%',
    top: 0,
    left: '0.98%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  newsApp: {
    position: 'absolute',
    top: 302,
    left: 47,
    width: 307,
    height: 88,
    cursor: 'pointer',
  },
  rulesChild: {
    position: 'absolute',
    top: 9,
    left: 0,
    backgroundColor: '#ff0000',
    width: 307,
    height: 66,
    opacity: 0.5,
  },
  rules: {
    position: 'absolute',
    top: 416,
    left: 47,
    width: 307,
    height: 88,
    cursor: 'pointer',
  },
  casual: {
    position: 'absolute',
    top: 526,
    left: 47,
    width: 307,
    height: 88,
    cursor: 'pointer',
  },
  topics: {
    position: 'absolute',
    top: 638,
    left: 47,
    width: 307,
    height: 88,
    cursor: 'pointer',
  },
  forumHomeScreen: {
    width: '100%',
    position: 'relative',
    height: 874,
    textAlign: 'center',
    fontSize: 36,
    color: '#000',
    fontFamily: 'Bungee',
  },
});

export default styles;
