import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  forumRulesScreen: {
    flex: 1,
    position: 'relative',
    textAlign: 'center',
    fontSize: 15,
    color: '#f9c74f',
    fontFamily: 'Bungee', // Ensure this font is available
  },
  forumRulesScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 917,
    resizeMode: 'cover',
  },
  rules: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '7.21%',
    left: '4.48%',
    fontSize: 48,
    fontFamily: 'Bungee Shade',
    color: '#fff',
    textAlign: 'center',
    alignSelf: 'center',
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 63,
    left: 2,
    width: 48,
    height: 48,
    overflow: 'hidden',
  },
  arrowLeftIconImage: {
    width: '100%',
    height: '100%',
  },
  selector: {
    position: 'absolute',
    top: 201,
    left: 0,
    backgroundColor: '#000',
    width: '90%',
    height: 582,
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
  category: {
    position: 'absolute',
    left: '5%',
    width: '90%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryChild: {
    backgroundColor: '#d9d9d9',
    width: '100%',
    height: 68,
    opacity: 0.7,
  },
  alexH: {
    position: 'absolute',
    top: '82%',
    left: '6.06%',
    color: '#000',
  },
  date: {
    position: 'absolute',
    top: '81.52%',
    left: '83.23%',
    color: '#000',
  },
  categoryLabel: {
    position: 'absolute',
    height: '88%',
    width: '100%',
    top: 0,
    left: 0,
    fontSize: 32,
    color: '#000',
    textAlign: 'center',
    justifyContent: 'center',
  },
});
