// styles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  userSearchScreen: {
    width: '100%',
    position: 'relative',
    height: 874,
    textAlign: 'left',
    fontSize: 16,
    color: '#b3b3b3',
    fontFamily: 'Inter', // Global font family
  },
  userSearchScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 917,
    resizeMode: 'cover', // Object-fit equivalent in React Native
  },
  suggested: {
    position: 'absolute',
    height: '11.56%',
    width: '85.32%',
    top: '13.27%',
    left: '7.21%',
    fontSize: 36,
    fontFamily: 'Bungee', // Global font family
    color: '#d63031',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  username: {
    flex: 1,
    position: 'relative',
    lineHeight: 100,
  },
  input: {
    position: 'absolute',
    top: 65.5,
    left: 40.5,
    borderRadius: 8,
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#f9c74f',
    width: 321,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 12,
    minWidth: 240,
  },
  input1: {
    position: 'absolute',
    top: 216.5,
    left: 40.5,
    borderRadius: 8,
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#d63031',
    width: 321,
    height: 51,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 12,
    minWidth: 240,
  },
  input2: {
    position: 'absolute',
    top: 321.5,
    left: 40.5,
    borderRadius: 8,
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#d63031',
    width: 321,
    height: 51,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 12,
    minWidth: 240,
  },
  magnifyingGlassIcon: {
    position: 'absolute',
    top: 66,
    left: 296,
    width: 49,
    height: 50,
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
});

export default styles;
