// styles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  yourAccountScreenChild: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 917,
    resizeMode: 'cover', // Object-fit equivalent in React Native
  },
  userName: {
    position: 'absolute',
    height: '15.79%',
    width: '91.04%',
    top: '1.72%',
    left: '10.45%',
    fontSize: 48,
    fontFamily: 'Bungee Shade', // Referencing global font styles if necessary
    color: '#fff',
    textAlign: 'center', // Centered alignment for user name
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeButtonIcon: {
    position: 'absolute',
    top: 797,
    left: 160,
    width: 82,
    height: 77,
  },
  trendingPosts1: {
    position: 'absolute',
    top: 21,
    left: 0,
    backgroundColor: '#f9c74f',
    width: 356,
    height: 146,
    opacity: 0.7,
  },
  trendingPosts2: {
    position: 'absolute',
    height: '52.69%',
    width: '96.35%',
    top: 0,
    left: '1.69%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trendingPosts: {
    position: 'absolute',
    top: 416,
    left: 23,
    width: 356,
    height: 167,
  },
  lastVisited1: {
    position: 'absolute',
    top: 27,
    left: 0,
    backgroundColor: '#f9c74f',
    width: 356,
    height: 146,
    opacity: 0.7,
  },
  lastVisited2: {
    position: 'absolute',
    height: '50.87%',
    width: '96.35%',
    top: 0,
    left: '1.69%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lastVisited: {
    position: 'absolute',
    top: 583,
    left: 23,
    width: 356,
    height: 173,
  },
  optionsChild: {
    position: 'absolute',
    top: 0,
    left: 91,
    backgroundColor: '#d9d9d9',
    width: 402,
    height: 79,
  },
  optionsItem: {
    position: 'absolute',
    top: 81,
    left: 91,
    backgroundColor: '#d63031',
    width: 356,
    height: 49,
    opacity: 0.7,
  },
  bookmarkIcon: {
    position: 'absolute',
    top: 10,
    left: 91,
    width: 61,
    height: 59,
  },
  settingsIcon: {
    position: 'absolute',
    top: 7,
    left: 412,
    width: 79,
    height: 61,
  },
  pencil03Icon: {
    position: 'absolute',
    top: 4,
    left: 245,
    width: 73,
    height: 71,
  },
  tagNa: {
    position: 'absolute',
    height: '64.74%',
    width: '69.57%',
    top: '35.26%',
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  options: {
    position: 'absolute',
    top: 260,
    left: -91,
    width: 493,
    height: 156,
  },
  profilePicture: {
    position: 'absolute',
    top: 126,
    left: 142,
    borderRadius: 50,
    backgroundColor: '#d9d9d9',
    width: 118,
    height: 114,
  },
  arrowLeftIcon: {
    position: 'absolute',
    top: 60,
    left: 5,
    width: 48,
    height: 48,
  },
  arrowLeftIconImage: {
    width: '100%',
    height: '100%',
  },
});

export default styles;
